export  const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71D-xbvtz-L._SX522_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/81CgtwSII3L._SX679_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51T183S4pSL._AC_UY327_FMwebp_QL65_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71v2jVh6nIL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/41qxYgCpJEL.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/71LRY1j6UHL._AC_UL480_FMwebp_QL65_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
        id: 10,
        category: 'mobiles',
        title: "Apple iPhone 6",
        imgSrc: 'https://m.media-amazon.com/images/I/31laW9Ex46L._SY445_SX342_QL70_FMwebp_.jpg',
        amazonLink: 'https://amzn.to/3PuckZp',
        description: 'Apple iPhone 14 (128 GB) - Blue',
        price: '89999',
      },
      {
        id: 11,
        category: 'mobiles',
        title: "Realme 12 Pro 5G",
        imgSrc: 'https://m.media-amazon.com/images/I/51cWjoblvVL._SY300_SX300_.jpg',
        amazonLink: 'https://amzn.to/3PuckZp',
        description: ' realme 12 Pro 5G submarine Blue, 8GB RAM 256 GB Storage',
        price: '19999',
      },  {
        id: 12,
        category: 'mobiles',
        title: "Redmi Note 13 5G ",
        imgSrc: 'https://m.media-amazon.com/images/I/710bX+jrz-L._SX679_.jpg',
        amazonLink: 'https://amzn.to/3PuckZp',
        description: 'Prism Gold, 6GB RAM, 128GB Storage) | 5G Ready | 120Hz Bezel-Less AMOLED | 7.mm Slimmest Note Ever | 108MP Pro-Grade Camera',
        price: '48999',
      },


  ]